Apra-Labs/ApraPipes

base/src/NvArgusCameraHelper.cpp, base/test/nvarguscamerahelper_tests.cpp
2.Added a testcase to nvarguscamerahelper_tests
=> 1.Updated NvArgusCameraHelper

README.md
* Added setup section for submodule
* Added update section for submodule
=> Added Recursive submodule installation and Setup Phase

.github/workflows/cmake.yml, base/test/filereadermodule_tests.cpp, base/test/filewritermodule_tests.cpp, base/test/module_tests.cpp, base/test/webcam_source_tests.cpp
Fixes #[Issue]
**Type**
**Checklist**
=> attempt to run all passing tests on cloud

base/include/NvArgusCamera.h, base/include/NvArgusCameraHelper.h, base/src/NvArgusCamera.cpp, base/src/NvArgusCameraHelper.cpp, base/test/nvarguscamera_tests.cpp, base/test/nvarguscamerahelper_tests.cpp
Modified Argus Camera Module to handle multiple cameras
**Type**
Type Choose one: (Feature )
**Checklist**
=> Argus camera modified

base/include/WebCamSource.h, base/src/WebCamSource.cpp
=> fix for BGR output, also setting width and height in opencv

docs/index.html
To fix github pages
Host documentation on github pages
No
**Type**
Type Choose one: Documentation 
**Checklist**
=> Add redirect for github pages

README.md
Fixes #[Issue]
**Type**
**Checklist**
=> Update readme and add docs link

.github/workflows/CI-cuda.yml, .github/workflows/CI.yml, base/test/gstrtsponvifsink_tests.cpp
cuda build runs on a docker container
=> try cuda build in CI

.github/workflows/CI-win.yml, .github/workflows/CI.yml, base/fix-vcpkg-json-win.ps1
Fixes #[Issue]
**Type**
**Checklist**
=> try windows 2 step build

base/test/sound_record_tests.cpp, base/test/test_utils.h
Fixes #77 
FileCleaner is added which clears the files generated during test cases.
**Type**
**Checklist**
=> Sound record Cleanup

base/CMakeLists.txt, base/include/Utils.h, base/src/PipeLine.cpp, base/src/Utils.cpp, base/test/pipeline_tests.cpp
Fixes #35 
Setting threadname in windows and Linux.  Added test for the same
none
**Type**
Type Choose one: Feature
**Checklist**
=> Putting module name as threadname

base/CMakeLists.txt, base/include/Command.h, base/include/Module.h, base/include/ValveModule.h, base/src/ValveModule.cpp, base/test/valveModule_tests.cpp
Fixes #127 
**Type**
Type Choose one: Feature
**Checklist**
=> ValveModule Implementation 

base/test/nvjpeg_combo_tests.cpp
Fixes #28 
The path for filereader is changed. 
**Checklist**
=> fileReader init() issue 

code-style-guide.md
Fixes #145 
To come up with proper coding guidelines for the framework. This PR is just the inital state and requires refining and discussion. 
None
**Type**
Type Choose one: Documentation 
**Checklist**
=> inital coding guidelines

README.md
Fixes #[Issue]
While building Aprapipes we require openssl also 
**Type**
Type Choose one: (Bug fix)
**Checklist**
=> Aprapies require openssl also

base/src/ValveModule.cpp, base/test/valveModule_tests.cpp
Fixes #136 
Improvements to Valve Module. Valve (sieve disabled) behavior is working and counting frames is based on pinId. Testcase for multiple frame type is also added to test updates.
Type Choose one: feature
**Checklist**
=> Improvements to ValveModule 

.github/workflows/build-test-lin-container.yml, .github/workflows/build-test-lin-wsl.yml, .github/workflows/build-test-lin.yml, .github/workflows/build-test-win.yml, base/src/CudaMemCopy.cpp, base/test/cudamemcopy_tests.cpp
tests on old linux cuda builder get stuck due to cudaMemCpy failed... this PR is to try fixes to the same
=> better logging for the linux test issue

.gitignore, base/CMakeLists.txt, base/include/BufferMaker.h, base/include/FileReaderModule.h, base/include/FileSequenceDriver.h, base/include/Module.h, base/src/FileReaderModule.cpp, base/src/FileSequenceDriver.cpp, base/src/Module.cpp, base/test/eglrenderer_test.cpp, base/test/filereadermodule_tests.cpp, base/test/jpegencoderl4tm_tests.cpp, base/test/l4tm_dec_enc_1_tests.cpp, base/test/log_stress_tests.cpp, base/test/mp4writersink_tests.cpp, base/test/multiple_pipeline_tests.cpp, base/test/nv_mp4_file_tests.cpp, base/test/rtsppusher_tests.cpp, docs/build/html/Framework.html, docs/build/html/_sources/Framework.rst.txt, docs/source/Framework.rst
BufferMaker is added as a generic concept for others to use. FFBufferMaker makes frames from modules factory.
=> Improved FileReader to not require a maxSize.

base/include/PipeLine.h, base/src/PipeLine.cpp, base/test/pipeline_tests.cpp
Fixes #128 
Added a method to flush all queues throughout the pipeline across
None
**Type**
Type Choose one:  Feature
**Checklist**
=> Implemented a FlushAllQueues functionality via pipeline interface

base/include/Logger.h, base/src/Logger.cpp
Fixes #205 
scope lock in the initLogger
None
**Type**
Type Choose one: Bug fix 
**Checklist**
=> fix for possible race condition in initLogger

base/test/ImageEncodeCV_tests.cpp, base/test/opencvresize_tests.cpp, base/vcpkg.json
Fixes #214 
This PR should fix the OpenCV build in arm64
**Type**
Type Choose one: (Bug fix )
**Checklist**
=> OpenCV build fix

base/vcpkg.json
Fixes #[Issue]
**Type**
**Checklist**
=> Vcpkg mirror links fix

.github/workflows/CI-Linux-CUDA-Docker.yml, .github/workflows/build-test-lin-container.yml, .github/workflows/build-test-lin-wsl.yml, .github/workflows/build-test-lin.yml, .github/workflows/build-test-win.yml, README.md
Fixes #[Issue]
**Type**
**Checklist**
=> fixed docker build

base/vcpkg.json
This PR will fix header file issue in baresip and libre vcpkg build.
**Type**
**Checklist**
=> vcpkg build fixed 

base/vcpkg.json
Fixes outdated link / failing link in vcpkg served by NASM server
**Type**
**Checklist**
=> updated URL in vcpkg update

README.md
Small change in readme (adds with or without cuda line)
**Type**
**Checklist**
=> readme small fix

base/vcpkg.json
Updated the mp4_box_reader.c in libmp4 to set the codec in Mpeg-4. Also updated the libmp4 port in vcpkg to use the updated changes of libmp4.
**Type**
Type Choose one: (Feature)
**Checklist**
=> Updated the Libmp4 port 

base/test/framesmuxer_tests.cpp
Fixes Nothing
Added a UT in muxer for drop strategy
No
**Type**
Type Choose one:  Testing 
**Checklist**
=> tested drop with muxer

knowledge_docs/Color_conversion_module.md, knowledge_docs/H.264_decoder_module.md, knowledge_docs/H.264_reverse_play.md, knowledge_docs/Motion_vector_calculation.md, knowledge_docs/Mp4ReaderSource_module.md, knowledge_docs/Mp4Writer_module.md, knowledge_docs/Overlay_module.md
Fixes #[Issue]
Contains knowledge docs of color conversion module , h264 bitstream anf h264 reverse play feature
**Type**
Type Choose one: Documentation
**Checklist**
=> knowledge docs

.github/workflows/build-test-lin-container.yml, .github/workflows/build-test-lin-wsl.yml, .github/workflows/build-test-lin.yml, .github/workflows/build-test-win.yml, .github/workflows/doxy.yml, .github/workflows/publish-test.yml, base/CMakeLists.txt
Fixes #[Issue]
**Type**
**Checklist**
=> fix upload-artificat action as v3 is deprecated

base/include/ArchiveSpaceManager.h, base/src/ArchiveSpaceManager.cpp
Fixes #[Issue]
There were a few issue in ArchiveSpaceManager - produce, sampling rate logic. These are fixed now. 
**Type**
Type Choose one: Bug fix 
**Checklist**
=> ArchiveSpaceManager fixes
