Apra-Labs/ApraPipes

base/include/Module.h
base/test/module_tests.cpp

There were 3 factory constructor for module props which can be replaced with default values in single constructor

Refactored ModuleProps Constructor Overloading

---

base/CMakeLists.txt
base/include/BrightnessContrastControl.h
base/include/VirtualPTZ.h
base/src/BrightnessContrastControl.cpp
base/src/VirtualPTZ.cpp
base/test/brightness_contrast_tests.cpp
base/test/virtualptz_tests.cpp

1. Brightness Contrast Module
2. VirtualPTZ module

Added VirtualPTZ Module and BrightnessContrast Module

---

.github/workflows/cmake_linux_x64_no_cuda.yml
.github/workflows/cmake_windows_x64_no_cuda.yml
base/include/CommonDefs.h
base/include/FilenameStrategy.h
base/include/FrameContainerQueue.h
base/include/Logger.h
base/include/PipeLine.h
base/include/QuePushStrategy.h
base/vcpkg.cuda.json
base/vcpkg.jetson.json
base/vcpkg.json
build_windows.bat

Fixes #65 
Description
Using a branch from the vcpkg fork . Made changes to version/baseline.json to pin boost to 1.76.0
Alternative(s) considered
Yes the other alternative is to override all boost libraries. But this will clutter the manifest.json file. Used Method 2 described here https://github.com/vicroms/vcpkg/blob/versioning/docs2/docs/examples/modify-baseline-to-pin-old-boost.md
Type Choose one: Bug fix
**Checklist**

Pin boost versions

---

base/CMakeLists.txt

This is a trivial issue. I have fixed CMakeLists include errors for VirtualCameraSink.
Upon running the bulid_jetson script, the nvarguscamera_tests throws error stating an undefined reference to the class of VirtualCameraSink.
The issue was with the flag used to include the VirtualCameraSink source and include files. Updating the flag from LINUX to ENABLE_LINUX fixed the issue.
--
**Type**
Bug fix
**Checklist**

Updated LINUX flag to ENABLE_LINUX in base/CMakeLists.txt

---

.gitignore
base/vcpkg.cuda.json
base/vcpkg.jetson.json
base/vcpkg.json

update the vcpkg to revision where cudnn can be built on jetsons.

try build with updated vcpkg

---

base/include/Module.h
base/src/Module.cpp
base/test/module_tests.cpp

Fixes #117 
- Added support for disabling sieving of input pins.
- Added a flag called `sieve` in `setNext` methods to allow passing through of input pins of the module as output pins as well. 
- Updated core `setNext` logic.
- If a module has at least one connection with sieve disabled, the number of `EOP` frames sent downstream are equal to sum of number of input and output pins of the module.
- None
**Type** 
- Feature
**Checklist**

added support for disabling sieve

---

base/include/Module.h
base/src/Module.cpp
base/test/module_tests.cpp

Fixes #119 
Updated the `getNumberOfOutputPins` to take implicit argument. Considers input pins too if implicit is false.
None
**Type**
- Feature 
**Checklist**

Sieve compliance

---

base/test/filewritermodule_tests.cpp

Fixes #123
Removed the duplicate FileCleaner from the test. Imported from test_utils
None
**Type**
- Bug/Testing

Use FileCleaner from test utils

---

base/include/BoundBuffer.h
base/include/FrameContainerQueue.h
base/include/Module.h
base/src/FrameContainerQueue.cpp
base/src/Module.cpp
base/test/module_tests.cpp

Fixes #125
- Implemented flushQue feature. 
-  On calling flushQue for a module, all the frames in the queues of downstream modules in the pipeline subtree are flushed.
None
**Type**
Type Choose one: Feature
**Checklist**

Implemented Flush Queue functionality for modules

---

base/src/ArchiveSpaceManager.cpp
base/src/MultimediaQueueXform.cpp

The return warning for ArchiveSpaceManager and MultimediaQueueXForm is solved.
**Type**
**Checklist**

Return Warning Fix

---

base/include/H264Utils.h
base/include/Mp4WriterSinkUtils.h
base/src/H264Utils.cpp
base/src/Mp4WriterSink.cpp
base/src/Mp4WriterSinkUtils.cpp
base/src/MultimediaQueueXform.cpp
base/test/mp4writersink_tests.cpp

Fixes #[Issue]
parseNalu function fixed , now the function will take const const_buffer as argument so now incoming image wont get tampered. In the mp4Writer module for h264 case , whenever the path of file changed the last video got ended without waiting for an i-frame to arrive , fixed the issue.
**Type**
Type Choose one: (Bug fix )
**Checklist**

parseNalu function and mp4Writer filePathName fix.

---

base/include/Mp4WriterSink.h
base/include/Mp4WriterSinkUtils.h
base/src/Mp4WriterSink.cpp
base/src/Mp4WriterSinkUtils.cpp
base/test/mp4writersink_tests.cpp
data/Metadata/metadata0.txt
data/Metadata/metadata1.txt
data/Metadata/metadata2.txt
data/Metadata/metadata3.txt
data/Metadata/metadata4.txt

Fixes #[Issue]
**Description : We can now write a video with any custom name given by the user.
**Type**
Type Choose one: (Feature)
**Checklist**

Custom file name for a video feature and write timestamp in the video header

---

base/fix-vcpkg-json.sh
build_linux_no_cuda.sh

Fixes #196 
built fix-vcpkg-json.sh which is equivalent of fix-vcpkg-json.ps1, which will resolve linux_nocuda build issue 
no
**Type**
**Checklist**

fixed linux_nocuda build issue

---

base/include/Mp4ReaderSource.h
base/include/Mp4ReaderSourceUtils.h
base/include/Mp4WriterSink.h
base/src/Mp4ReaderSource.cpp
base/src/Mp4ReaderSourceUtils.cpp
base/src/Mp4WriterSink.cpp
base/test/mp4readersource_tests.cpp
base/test/mp4writersink_tests.cpp

…ader waits untill video gets written on disk
Fixes #[Issue]
1. Dts calculation strategy for mp4writer
2. Added feature Parse Root directory to find video in mp4reader. 
3. Mp4reader waits if no video is present in the given dir,  untill new video is written on disk.
**Type**
Type Choose one: (Feature )
**Checklist**

Mp4Reader and Mp4Writer changes

---

base/include/RawImagePlanarMetadata.h
base/test/imagemetadata_tests.cpp

Fixes #208
updated RawImagePlanarMetadata which takes a array of four integers in the constructor and  use these pointers instead of calculating the offsets itself.
No
**Checklist**

EnhancedRawImagePlanarMetadata

---

base/test/cudamemcopy_tests.cpp

Fixes #[Issue]
The cuda tests fail on linux cuda self host machine due to the machine's low cuda compute capability , so to avoid the failure added compute cap precondition in the CudaMemcpyTest
**Type**
**Checklist**

Added cuda compute cap precondition to cudaMemcpyTests

---

base/test/jpegdecoderl4tm_tests.cpp
base/test/jpegencoderl4tm_tests.cpp
base/test/l4tm_dec_enc_1_tests.cpp

Fixes #[Issue]
Disabled all jpegEncoderL4tm and jpegDecodetL4tm tests
**Type**
**Checklist**

Arm build fix

---

base/vcpkg.json

This PR fixes the vcpkg build of baresip. The issue of hardcoded path for baresip to find re is resolved. 
**Type**
Type Choose one: Bug fix

vcpkg build fix 

---

base/include/DMAAllocator.h
base/test/frame_factory_test_dma.cpp

Fixes #237 
added two more arguments pitch,offset to the DMAAllocator setMetadata whose default values will be null , if we pass those with some random values and call DMAAllocator setMetadata API i will return correct offset and pitch values for respective DMA buffer
NO
**Checklist**

Enhanced DMAllocator setMetadata

---

base/include/ApraNvEglRenderer.h
base/include/Command.h
base/include/EglRenderer.h
base/src/EglRenderer.cpp
base/src/NvEglRenderer.cpp
base/test/eglrenderer_test.cpp

Fixes #243 
implemented two new features, one was creating & destroying EglRenderer window during run time , the other was adding flag through which renderer can or can't be manager via window manager
NO
Type Choose one: Feature
**Checklist**

EnhancedEglRenderer

---

base/src/Mp4WriterSink.cpp

Fixes #285 
Made requested changes
Other ways did not pan out
**Type**
Type Choose one: (Bug fix) 
**Checklist**

write 0 sized entries in metadata track to ensure sync

---

base/src/DMAFDWrapper.cpp
base/test/frame_factory_test_dma.cpp

Fixes #278 
currently with memcpy we were just able to read the buffer we are unable to write , so i change it to Read_write 
we had three enum's  read , write , read_write wen can have support of three and make it user choice , but we have to change so many modules internally can implement this in future
**Checklist**

EnhancedDMAFDWrapper

---

base/src/Mp4WriterSink.cpp
base/test/mp4writersink_tests.cpp

Fixes #[Issue]
Fixes the bug in Mp4Writer, where the frame size was getting appended only to last two bytes of nalu separator , instead it should it all the four bytes of nalu separator to save the frame size. Because frame size cross 2^16 - 1 which is more than 2 bytes.
**Type**
**Checklist**

Mp4 Writer video playback compatibility fix for high resolution videos

---

base/CMakeLists.txt
base/include/ImageViewerModule.h
base/src/ImageViewerModule.cpp
base/test/imageviewermodule_tests.cpp

Fixes #282 
Merged Eglrenderer module into imageviewer module now we have one renderer module , if device is arm and memtype is dma it uses egl for rendering else it uses imageviewer(opencv->imshow)
NO
Type Choose one: Enhancement
**Checklist**

GenericRendererModule

---

base/include/Mp4ReaderSource.h
base/src/Mp4ReaderSource.cpp
base/test/mp4readersource_tests.cpp

Fixes #273 
Did Mp4Reader changes related to following cases and added test for them:
Changing file path from custom file name to only root dir and vice versa.
Changing filename to only root dir and vice versa.
**Type**
**Checklist**

Mp4Reader getSetProps enhancement

---

base/include/ColorConversionXForm.h
base/src/ColorConversionXForm.cpp

Fixes #[Issue]
The setMetadata for color conversion module was happening in addInput pin method, but this was having issues as other modules setMetadata during processSOS. Moved the setMetadata in the processSOS method, and the input pin verification happens in processSOS.
**Type**
**Checklist**

Color conversion module bug fix

---

base/src/Mp4WriterSink.cpp
base/vcpkg.json

Fixes #302 
Fixed the frame_sp buffer modify issue. Earlier the input frame_sp->data() (Nalu seperators) used to get updated to support the video playback capability across all the players. To avoid modifying the frame buffer added a new method in libmp4 to take two buffers, i.e. modified nalu seprators buffer and the incremented frame buffer pointer.
**Type**
Type Choose one: (Bug fix)
**Checklist**

Fixed Mp4Writer frame buffer modify issue

---

.github/workflows/build-test-win.yml
base/include/Mp4WriterSinkUtils.h
base/src/Mp4ReaderSource.cpp
base/vcpkg.json

In the Mp4reader (h264), The PR fixes the  issue of decoding frames with high resolution. In the Mp4Reader we convert the mp4 format nalu separator to standard H.264 nalu format, earlier we were only converting last two bytes of nalu separator to standard format where the frame's size is written, but for the high resolution video where the frame's size is greater than 2 ^ 16 , 3 bytes of nalu separator were getting used and because of that one byte was not getting converted. Updated the code to convert all 4 bytes of nalu separator to standard H.264 format./
Have you considered any alternatives? And if so, why have you chosen the …

Mp4Reader - Fixed high resolution video playback issue

---

base/include/Command.h
base/include/H264Decoder.h
base/include/Mp4ReaderSource.h
base/include/Mp4WriterSinkUtils.h
base/include/MultimediaQueueXform.h
base/src/H264Decoder.cpp
base/src/Mp4ReaderSource.cpp
base/src/MultimediaQueueXform.cpp
base/vcpkg.json

Implemented feature to supoort change of speed playaback speed dynamically . The range of speed are from 0.5x to 32x
**Type**
**Checklist**

Playback speed control feature

---

base/CMakeLists.txt
base/src/Mp4WriterSinkUtils.cpp
base/src/MultimediaQueueXform.cpp
base/src/QRReader.cpp
base/vcpkg-configuration.json
base/vcpkg.json
build_linux_cuda.sh
build_scripts/build_dependencies_linux_cuda.sh
build_scripts/build_dependencies_linux_no_cuda.sh
thirdparty/custom-overlay/baresip/portfile.cmake
thirdparty/custom-overlay/baresip/vcpkg.json
thirdparty/custom-overlay/libmp4/portfile.cmake
thirdparty/custom-overlay/libmp4/vcpkg.json
thirdparty/custom-overlay/openh264-apra/0001-respect-default-library-option.patch
thirdparty/custom-overlay/openh264-apra/portfile.cmake
thirdparty/custom-overlay/openh264-apra/vcpkg.json
thirdparty/custom-overlay/re/portfile.cmake
thirdparty/custom-overlay/re/vcpkg.json

Fixes #341  #323
Updated vcpkg, moved libmp4, baresip, openh264 apra, re to custom overlays.
Added gtk3, glew and glfw to CMakelists from vcpkg
**Type**
**Checklist**

Update VCPKG to master branch 

---

.github/workflows/build-test-win.yml
README.md

Fixes #[Issue]
**Type**
**Checklist**

Bumped up the cudnn version to v11.8 in workflow

---

base/include/AbsControlModule.h
base/src/AbsControlModule.cpp

Issue - https://github.com/Apra-Labs/ApraPipes/issues/364

changed the function args from pipeline object to name

---

base/include/FramesMuxer.h
base/src/FramesMuxer.cpp
base/test/framesmuxer_tests.cpp

Fixes #[Issue]
The MaxDelayTimeStampStrategy is a component designed to manage the timing and synchronization of frames within a muxing system. Its primary function is to ensure that frames from multiple input sources are combined only if their timestamps are within a defined maximum delay threshold (maxTSDelay).
Key Features:
Timestamp-Based Synchronization: The strategy checks the timestamp difference between incoming frames and only processes frames that have a timestamp difference within the allowed maximum delay.
Flexibility: Configurable maxTSDelay allows adjustment of the acceptable delay between frames, accommodating various timing requirements and use …

Time muxer strategy

---

.gitmodules
README.md
base/CMakeLists.txt
base/include/QRReader.h
base/src/QRReader.cpp
base/test/QRReader_tests.cpp

Fixes #[Issue]
**Type**
**Checklist**

Qrreader changes

---

base/CMakeLists.txt
base/include/AbsControlModule.h
base/include/Module.h
base/include/PipeLine.h
base/include/SimpleControlModule.h
base/src/AbsControlModule.cpp
base/src/Module.cpp
base/src/PipeLine.cpp
base/src/SimpleControlModule.cpp
base/test/simpleControlModuleTests.cpp

Fixes #384 
Fixed bunch of issues in control module 
1. thread not joining issue 
2. cyclic dependency 
Added ability to print status of the control module as a serialized string
Added tests for control module (none existed) 
None
**Type**
Type Choose one: (Bug fix | Feature | Testing )
**Checklist**

control module pipeline fixes & added control module UTs

---

build_scripts/build_dependencies_jetson_cuda.sh
build_scripts/build_dependencies_linux_cuda.sh
build_scripts/build_dependencies_linux_no_cuda.sh

Fixes #[Issue]
pip installs the latest version of cmake (current version ~4.0.0). This is incompatible with some of the packages that are listed in vcpkg.json
This change will install version 3.29.6 which is compatible with the packages.
**Type**
**Checklist**

Force build scripts on linux to install cmake version 3.29.6
